name: pokekoto
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_database: ^1.0.1
  google_sign_in: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/image_bg00.png
    - assets/images/image_bg01.png
    - assets/images/splash.png
